name: Build/Test frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:  
  frontend-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm ci
          working-directory: frontend

        # - name: Run tests
        #   run: npm run test
        #   working-directory: frontend

        - name: Build frontend
          run: npm run build
          working-directory: frontend

        - name: Commit and push frontend build
          run: |
            git config user.name "CI Bot"
            git config user.email "ci@example.com"
            
            # Create a folder to store builds (optional: separate branch)
            git checkout -b builds
            
            # Copy dist/ to repo
            rm -rf frontend/frontend-build
            cp -r frontend/dist frontend/frontend-dist
            
            git add .
            git commit -m "CI: Add latest frontend build [skip ci]"
            
            # Push using token
            git push http://prajwol:${{ secrets.GITEA_TOKEN }}@host.docker.internal:3000/prajwol/artist.git builds --force



