name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_sqlite, gd

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: backend

      - name: Generate app key
        run: php artisan key:generate
        working-directory: backend

      - name: Setup environment
        run: cp backend/.env.testing backend/.env

      - name: Run migrations
        run: php artisan migrate --database=sqlite --force
        working-directory: backend
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run tests
        run: php artisan test --migrate-configuration
        working-directory: backend
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
